# Generated by Django 4.2 on 2023-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='anulate',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nombre corto'),
        ),
    ]
