# Generated by Django 4.2 on 2023-04-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'ordering': ['titulo'], 'verbose_name': 'Prueba', 'verbose_name_plural': 'Pruebas'},
        ),
    ]
